Richardson level 3 implementation
vanmarcke/ocr_projet7_Bilemo pull request #32
Opened 2022-03-16 16:09 UTC by vanmarcke

Issue [#31]

Richardson level 3 implementation

2022-03-17 07:57 UTC, antoinetrouve requested changes
Mettre en place les groupes de serialization via la librairie JMS Serializer 
- https://jmsyst.com/libs/serializer/master/reference/annotations
- https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies

2022-03-17 07:57 UTC, antoinetrouve commented on config/packages/jms_serializer.yaml
> +#    metadata:
A supprimer si inutile sauf a des fins d'apprentissage

2022-03-17 07:57 UTC, antoinetrouve commented on src/Api/ApiHelper.php
> +        return new Response($error, Response::HTTP_NOT_FOUND, [
```suggestion
        return new JsonResponse($error, Response::HTTP_NOT_FOUND, []; true);
```

2022-03-17 07:57 UTC, antoinetrouve commented on src/Api/ApiHelper.php
> +    public function notFoundResponse(): Response
```suggestion
    public function notFoundResponse(): JsonResponse
```

2022-03-17 07:57 UTC, antoinetrouve commented on src/Api/ApiHelper.php
> +            'Content-Type' => 'application/json',
```suggestion
```

2022-03-17 07:57 UTC, antoinetrouve commented on src/Api/ApiHelper.php
> +        ]);
```suggestion
```

2022-03-17 07:57 UTC, antoinetrouve commented on src/Controller/ProductsController.php
> +        $json = $this->serializer->serialize($productsList, 'json');
As tu essayé la gestion des groupes de la librairie ? Il faut voir dans la documentation officielle de JMS Serializer : 
- https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies
- https://jmsyst.com/libs/serializer/master/reference/annotations

```suggestion
        $json = $this->serializer->serialize($productsList, 'json', SerializationContext::create()->setGroups(['show_products']));
```

2022-03-17 07:57 UTC, antoinetrouve commented on src/Controller/ProductsController.php
> -     *          @OA\Items(ref=@Model(type=Products::class, groups={"product"}))
Il faut garder la gestion des groupes

2022-03-17 07:57 UTC, antoinetrouve commented on src/Controller/ProductsController.php
> -            $this->serializer->serialize($product, 'json', ['groups' => 'product']);
idem

2022-03-17 07:57 UTC, antoinetrouve commented on src/Controller/UsersController.php
> -     *          @OA\Items(ref=@Model(type=Users::class, groups={"user"}))
Avec JMS tu peux garder la gestion des groupes de serializations

2022-03-17 07:57 UTC, antoinetrouve commented on src/Entity/Products.php
> +    #[Serializer\Groups(["show_products", "product"])]
Tu mets les groupes en place mais tu les utilises pas ?

2022-03-17 08:16 UTC, antoinetrouve commented on src/Api/ApiHelper.php
> +        return new Response($error, Response::HTTP_NOT_FOUND, [
Ha mon avis ca fonctionnait pas d'une part à cause de JMS mais aussi parce que tu utilisais mal la fonction JsonResponse. A cette fonction **il faut lui spécifiée le format de tes données** (d'ou le dernier paramètre à mettre à `true` si tes données sont déjà formatté en json).

2022-03-17 08:29 UTC, antoinetrouve commented on src/Entity/Products.php
>  class Products
Je n'avais pas fait attention mais il te manque la documentation sur tes propriétés -> en dessous de https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#general-php-objects + `@OA\Property`

2022-03-17 10:22 UTC, vanmarcke commented on src/Api/ApiHelper.php
> +        ]);
Done

2022-03-17 10:22 UTC, vanmarcke commented on src/Api/ApiHelper.php
> +            'Content-Type' => 'application/json',
done

2022-03-17 10:22 UTC, vanmarcke commented on src/Api/ApiHelper.php
> +    public function notFoundResponse(): Response
done

2022-03-17 10:27 UTC, vanmarcke commented on src/Api/ApiHelper.php
> +        return new Response($error, Response::HTTP_NOT_FOUND, [
done

2022-03-17 15:46 UTC, vanmarcke commented on src/Controller/ProductsController.php
> +        $json = $this->serializer->serialize($productsList, 'json');
done

2022-03-17 15:46 UTC, vanmarcke commented on src/Controller/ProductsController.php
> -     *          @OA\Items(ref=@Model(type=Products::class, groups={"product"}))
done

2022-03-17 15:46 UTC, vanmarcke commented on src/Controller/ProductsController.php
> -            $this->serializer->serialize($product, 'json', ['groups' => 'product']);
done

2022-03-17 15:47 UTC, vanmarcke commented on src/Entity/Products.php
> +    #[Serializer\Groups(["show_products", "product"])]
done

2022-03-18 14:00 UTC, vanmarcke commented on src/Controller/UsersController.php
> -     *          @OA\Items(ref=@Model(type=Users::class, groups={"user"}))
done

2022-03-18 14:01 UTC, vanmarcke commented on src/Entity/Products.php
>  class Products
done : 
use JMS\Serializer\Annotation\Type;
#[Type("integer")] .....

2022-03-21 07:43 UTC, antoinetrouve approved these changes

2022-03-21 07:43 UTC, antoinetrouve commented on src/Controller/UsersController.php
> +        // $json = $this->serializer->serialize($usersList, 'json', SerializationContext::create()->setGroups(array('show_users')));
A supprimer si plus besoin. Il n'y a pas besoin de groupe ici ?

2022-03-21 08:50 UTC, vanmarcke commented on src/Controller/UsersController.php
> +        // $json = $this->serializer->serialize($usersList, 'json', SerializationContext::create()->setGroups(array('show_users')));
done

2022-03-21 09:11 UTC, merged